name: Cross-Platform Build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            suffix: ""
          - os: windows-latest
            goos: windows
            suffix: ".exe"
    
    steps:
    - name: 1. Project checkout
      uses: actions/checkout@v4
    
    - name: 2. Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: 4. Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: amd64
      run: |
        mkdir -p bin
        go build -o bin/demo-${{ matrix.goos }}-amd64${{ matrix.suffix }} main.go
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/
